name: Versioning

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dev dependencies
        run: uv sync --extra dev

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Semantic Release - version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv run semantic-release version

      - name: Push version bump commit and tags
        if: always()
        run: |
          # Push the commit (if any) and the annotated tag(s) that point to HEAD
          git push origin HEAD:main --follow-tags

      - name: Get new tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "")
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Dispatch Release workflow with tag
        if: steps.get_tag.outputs.tag != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run release.yml -f tag="${{ steps.get_tag.outputs.tag }}"
